export REACT_APP_FIREBASE_API_KEY="AIzaSyAWo_u2ClzPBnfsO5Kd2iJsAfXvp76wq6A"
export REACT_APP_FIREBASE_AUTH_DOMAIN="lala-profile-web.firebaseapp.com"
export REACT_APP_FIREBASE_PROJECT_ID="lala-profile-web"
export REACT_APP_FIREBASE_STORAGE_BUCKET="lala-profile-web.appspot.com"
export REACT_APP_BASE_URL="http://52.79.98.34:38001"