version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.4
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/build

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  
      # TODO: run tests!zd
      - run: npm run build 
      - run: ssh -o StrictHostKeyChecking=no -i /home/circleci/.ssh/id_rsa ec2-user@ec2-52-78-179-249.ap-northeast-2.compute.amazonaws.com rm -rf /home/ec2-user/targets/lala-profile-web/build 
      - run: scp -o StrictHostKeyChecking=no -r /home/circleci/.ssh/id_rsa ./build ec2-user@ec2-52-78-179-249.ap-northeast-2.compute.amazonaws.com:/home/ec2-user/targets/lala-profile-web/
      - run: ssh -o StrictHostKeyChecking=no -i /home/circleci/.ssh/id_rsa ec2-user@ec2-52-78-179-249.ap-northeast-2.compute.amazonaws.com /home/ec2-user/targets/lala-profile-web/startup.sh
      

